spring.application.name=cafe

logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %yellow(%-5level) %red([%thread]) %blue(%logger{255}) - %msg%n}
#logging.level.org.hibernate.orm.jdbc.bind=trace
#logging.level.org.hibernate.orm.jdbc.extract=trace

spring.jpa.properties.hibernate.default_schema=dbo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CafeDB;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true

cafe.app.jwtSecret=YourSuperSecretKeyForDripLabCoffeeSystem2026!
cafe.app.jwtExpirationMs=86400000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
