spring.application.name=cafe

logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %yellow(%-5level) %red([%thread]) %blue(%logger{255}) - %msg%n}
#logging.level.org.hibernate.orm.jdbc.bind=trace
#logging.level.org.hibernate.orm.jdbc.extract=trace

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CafeDB;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true

#cafe.app.jwtSecret=YourSuperSecretKeyForDripLabCoffeeSystem2026!
#cafe.app.jwtExpirationMs=86400000